# Generated by Django 3.1.3 on 2020-11-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('major', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=9)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
