# Generated by Django 3.1.3 on 2020-11-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201123_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='courseselectioncode',
            new_name='coursesectioncode',
        ),
    ]
