# Generated by Django 3.1.3 on 2020-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201123_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(default='SOME STRING', max_length=500)),
                ('coursename', models.CharField(max_length=500)),
                ('courseselectioncode', models.IntegerField(default=0)),
                ('coursedepartment', models.CharField(default='SOME STRING', max_length=500)),
                ('instructorname', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='courseinfo',
            old_name='coursesectioncode',
            new_name='courseselectioncode',
        ),
    ]
